login/urls.py
from django.conf.urls import url

from login import views as view02
app_name='login'
urlpatterns = [
    url(r'^$', view02.login, name='login'),
    url(r'^admin/.*?', view02.login, name='login'),
    url(r'^logout/$', view02.logout, name="logout"),
    # url(r'.*?', views0.login,name='login'),
# ex: /login/abc123!   /login/ 为mysite已填好的前缀
    url(r'^index/$', view02.submit_login, name="submit_login"),
# ex: /login/index   /login/ 为mysite已填好的前缀
    url(r'^json1/$', view02.json1, name='json1'),
    url(r'^json2/$', view02.json2, name='json2'),
    url(r'^table/$', view02.table, name='table'),
    url(r'^ajax/$', view02.ajax, name='ajax'),
    url(r'^demo/$', view02.demo, name='demo'),

    url(r'^submit_form/$', view02.submit_form, name='submit_form'),
    url(r'^tab/$', view02.Active_tab, name='Active_tab'),
    url(r'^user_table/$', view02.user_table, name='user_table'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

#相当于映射各个项目的url


urlpatterns = [
    url(r'^login/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls'))]
    # url(r'^login/', views0.login),
    # ] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

login/models.py
#数据存储
import hashlib

from django.db import models
import django.utils.timezone as timezone
# Create your models here.

class UserInfo(models.Model):
    user=models.CharField(max_length=50,unique=True)
    pwd=models.CharField(max_length=50)

    #默认返回
    def __str__(self):
        return self.user
    class Meta:
        db_table = 'client_UserInfo' #自定义表名

    def save(self, *args, **kwargs):
        self.pwd = hashlib.sha1(self.pwd.encode("utf8")).hexdigest()
        super(UserInfo, self).save(*args, **kwargs)



class user_form(models.Model):

    def __str__(self):
        return self.title
    class Meta:
        db_table = 'client_user_form'

    order_no=models.CharField('表单id', max_length=50)
    title = models.CharField('标题', max_length=50)
    phone = models.CharField('电话', max_length=11,blank=True)
    # DecimalField(max_digits='数字允许的最大位数', decimal_places='小数的最大位数')：十进制浮点数
    money_min=models.DecimalField ('最小金额', max_digits=10,decimal_places=2)
    money_max=models.DecimalField ('最大金额', max_digits=10,decimal_places=2)
    password = models.CharField('密码', max_length=50)

    email = models.EmailField('邮箱', null=True)
    city=models.CharField('城市', max_length=50)
    hobbies=models.CharField('爱好', max_length=50,null=True)
    off_on=models.BooleanField('开关',default=True)
    #状态为0，1,2 对应'刚创建'，'开发中'，'已提测'
    status=models.IntegerField('状态',default=0)

    sex=models.CharField('性别',max_length=5)
    content=models.CharField('文本描述',max_length=150)
    add_date = models.DateTimeField('保存日期', default=timezone.now)
    update_time = models.DateTimeField('更新时间',auto_now=True)
    # DateTimeField和DateField和TimeField存储的内容分别对应着datetime(), date(), time()三个对象。
    search_time=models.DateField('按范围搜索日期', auto_now=False, null=True)
    search_times = models.CharField('按范围搜索日期',  max_length=50,null=True)

    def save(self, *args, **kwargs):
        self.password = hashlib.sha1(self.password.encode("utf8")).hexdigest()
        super(user_form, self).save(*args, **kwargs)

login/views.py
# 业务逻辑
from django.shortcuts import render,redirect,get_object_or_404
from .models import *  # 导入models文件

from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.contrib.auth.decorators import login_required
import hashlib
import time


# import json



# Create your views here.
@csrf_exempt
def login(request):
    # 通过下面的if语句，我们不允许重复登录：重定向
    if request.session.get('is_login')==True:
        return  render(request,'login/admin.html')
    if request.method == 'POST':
        # 模板中输入的信息变量
        username=request.POST.get('username')
        password=request.POST.get('password')

        pwd = hashlib.sha1(password.encode("utf8")).hexdigest()  # 对数据进行sha1加密
        print(pwd)
        message="所有字段都必须填写"
        # 确保用户名和密码都不为空
        if username and password:
            # 将账号去除空格 并传给 username变量
            username = username.strip()
            try:

                #get(user)为数据库的字段变量  user是一条查询信息
                userinfo = get_object_or_404(UserInfo, user=username)
                # userinfo =UserInfo.objects.get(user=username)

                #如果用户名密码正确 跳转首页
                # print(userinfo.pwd)
                if userinfo.pwd==pwd:
                    # print(userinfo.pwd,pwd)
                    #设置session变量
                    request.session['is_login'] = True
                    request.session['user_id'] = userinfo.id
                    request.session['user_name'] = userinfo.user

                    return render(request,'login/admin.html')

                # 密码错误打印 密码错误提示
                else:
                    message = '密码错误'

            except:
                # 该用户不存在 打印 该用户不存在
                message = '该用户名不存在'

        return render(request, 'login/login.html',locals())

    return render(request,'login/login.html')

@csrf_exempt
def submit_login(request):
    # if request.session.get('is_login') != True:
    #     return redirect('/login/')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        message="所有字段都必须填写"

        info = UserInfo()
        #这里要跟数据库字段一致
        info.user = username
        info.pwd = str(password)
        if username and password:
            # 将账号去除空格 并传给 username变量
            try:
                # get(user)为数据库的字段变量  user是一条查询信息
                userinfo = get_object_or_404(UserInfo, user=username)
                # print(userinfo.pwd)
                # userinfo =UserInfo.objects.get(user=username)

                # 如果用户名相等则提示已存在 否则进行存储
                if userinfo.user==username:
                    message = '该用户已存在'
                else:
                    info.save()
                    # UserInfo.objects.create(user=username, pwd=password)
                    message='用户提交成功'
            except:
                # UserInfo.objects.create(user=username, pwd=password)
                info.save()
                message = '用户提交成功'
        return render(request, 'login/index.html',locals())

    # 从数据库中读取所有数据，注意缩进
    user_list = UserInfo.objects.all()

    return render(request, 'login/index.html', {'data':user_list})


def logout(request):
    # flush次性将session中的所有内容全部清空
    request.session.flush()
    return render(request,'login/login.html')


# return HttpResponse('hello world!')


def json1(request):

    return render(request,'login/json1.html')

def json2(request):

    data= {'a': 'admin', 'b': '123456'}
    return JsonResponse(data)




def table(request):
    return render(request,'login/table.html')




# @csrf_exempt
# def check_submit(request):
#
#     # if request.method == 'POST':
#     username = request.POST.get('username')
#     password = request.POST.get('password')
#     ret = {'code': None, 'msg': None}
#     # if username and password:
#     #         print('ok')
#             # 将账号去除空格 并传给 username变量
#     try:
#         userinfo = get_object_or_404(UserInfo, user=username)
#         print('ok')
#         if userinfo.user==username:
#                 print('ok')
#                 if userinfo.pwd==password:
#
#                     ret['code']=2000
#                     print(ret)
#                     return HttpResponse(json.dumps(ret))
#
#                     # ret['msg']='登录成功'
#
#                 else:
#                     ret['code'] = 2001
#
#                     # ret['msg'] = '密码错误'
#
#         else:
#             ret['code'] = 2009
#             print(ret)
#             # ret['msg'] = '用户名不存在'
#
#     except:
#         pass
#
#
#     return HttpResponse(json.dumps(ret))



    # return HttpResponse(json.dumps(ret))
    # return render(request, 'login/demo.html')

def submit_form(request):
    if request.method == 'POST':
        print(request.POST)
        order_no = str(time.strftime('%Y%m%d%H%M%S', time.localtime(time.time())))+ str(time.time()).replace('.', '')[-7:]
        title=request.POST.get("title")
        money_min=request.POST.get("price_min")
        money_max=request.POST.get('price_max')
        phone=request.POST.get("phone")
        password=request.POST.get("password")
        email=request.POST.get("email")
        city=request.POST.get("city")
        hobbies=request.POST.get("hobbies")
        off_on=request.POST.get("on_off")
        sex=request.POST.get("sex")
        content=request.POST.get("texts")
        search_time=request.POST.get("time1")
        search_times = request.POST.get("times")

        #返回数据
        data = {'status': 200, 'msg': '提交成功', 'data':[money_min,money_max]}
        data1 = {'status': 400, 'msg': '金额错误,最大值必须大于最小值', 'data': [money_min,money_max]}

        #前端的值需转换
        if off_on=='on':
            off_on='True'
        else:
            off_on='False'

        # print(money_min)
        # print(type(money_min))
        if int(float(money_min))<=int(float(money_max)):
            user_form.objects.create(order_no=order_no,title=title,phone=phone,money_min=money_min,
                money_max=money_max,password=password,email=email,city=city,hobbies=hobbies,off_on=off_on,sex=sex
                ,content=content,search_time=search_time,search_times=search_times
            )
            return JsonResponse(data)
        else:
            return JsonResponse(data1)
    else:

        return JsonResponse('请求方法错误')





def user_table(request):

    # 同样支持链式条件过滤查询，如objects.values().filter(book_name=’test’)
    # 支持切片查询，如objects.values()[:10]
    # 支持字段过滤查询，如我只想查询id和book_name
    # 这两个字段，只需这样写
    data=user_form.objects.values().order_by('-id')[:10]
    content={}
    content['list']=list(data)
    content['code']=200
    content['msg']='请求成功'
    # print(len(content['list']))
    return JsonResponse(content)



# @login_required
def demo(request):
    return render(request, 'login/layui_demo.html')


def Active_tab(request):
    return render(request, 'login/Active_tab.html')


@csrf_exempt
def ajax(request):
    if request.method =='POST':
        print(request.POST)
        na=request.POST.get('data')
        # print(na)
        data = {'status': 2001, 'msg': '请求成功', 'data': [11, 22, 33, 4555, 55]}
        data1={'status': 1000, 'msg': '数据错误', 'data':'null'}
        if na=='0000':

            return JsonResponse(data)
        else:
            return JsonResponse(data1)

        # data={'status':0000,'msg':'请求成功','data':[11,22,33,4555,55]}
        # # print(type(JsonResponse(data)))
        # # print(type(json.dumps(data)))
        # return JsonResponse(data)

    else:
        return render(request,'login/ajax.html')

templates/login/ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ajax请求后台数据</title>
    <script src="https://cdn.bootcss.com/jquery/1.8.2/jquery.js"></script>

</head>
<body>
        <input  id="na" type="text" />
        <input type="button" value="点击执行ajax" onclick='Doajax()'/><br />
        <textarea  id="content" col="400" rows="5" placeholder="显示返回的值"></textarea>
        <script type="text/javascript">

            //执行点击操作 ajax
              function Doajax() {
                  var temp = $('#na').val();
                  console.log(temp);
                  if (temp.length != 0) {
                      $.ajax({
                          url: "{% url 'login:ajax' %}",
                          type: 'POST',
                          dataType: 'json',
                          //往后台传的值
                          //data temp 为输入的数据
                          data: {data: temp,
                              unid:'${formlist.items[0].unid}'
                          },

                          success: function (arg) {
                                console.log(arg);
                                //可以将后台返回的json对象转换成json对符串
                              var obj = JSON.stringify(arg);

                              $('#content').val( obj)
                          },
                          error: function () {
                              console.log('failed')

                          }
                      });

                  } else {
                      alert('未传值');
                      console.log('未传值');
                  }
              }
            </script>

</body>
</html>

templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试-运维平台</title>

    {#  注意引入文件的方式  #}
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="{% static 'layui-v2.4.3/layui/css/layui.css' %}" media="all">

    {#  设置网页标题图标  #}
    <link rel="icon" type="image/x-icon" href="/static/media/icon.ico" />

    {#  设置js文件  #}
    <script src="{% static "layui-v2.4.3/layui/layui.js" %}"></script>

</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <h1>用户输入：</h1>
    <form action="{% url 'login:submit_login' %}" method="post">
        {% csrf_token %}   <!--加入这行 -->
        用户名：<input type="text" name="username" id="name" placeholder="请输入名字" onblur="formcheck()" ><br />
        密码：<input type="password"  name="password"  placeholder="请输入密码" onblur="formcheck()"><br />
​        <button onclick="myFunction()">提交</button>
{#        <input type="submit" value="提交" id="btn">#}
     {#加入了message插件#}
        {% if message %}
            <div class="alert alert-warning">{{ message }}
            </div>
        {% endif %}

    </form>
{#弹框设置#}
{#    <script>#}
{#        function myFunction(){#}
{#            var a=document.getElementById("name").value;#}
{#        alert(a+"提交成功");#}
{#   </script>#}

    <h1>数据内容刷新页面：</h1>
        <table border="1">
            <thead>
                <tr>用户名</tr>
                <tr>密码</tr>
            </thead>
            <tbody>
                {% for item in data %}
                <tr>
                    <td>{{ item.user }}</td>
                    <td>{{ item.pwd }}</td>
                </tr>
                {% endfor %}
            <ul class="nav navbar-nav navbar-right">
              {% if request.session.is_login %}
                  <li><a href="#">当前在线：{{ request.session.user_name }}</a></li>

                  <li><a href="{% url 'login:logout' %}">登出</a></li>
              {% endif %}

            </ul>
            </tbody>
        </table>



{#    <script src="/static/js/jquery-3.3.1.min.js"></script>#}

templates/login/json1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>获取账号密码</title>

    <script src="https://cdn.bootcss.com/jquery/1.12.1/jquery.js"></script>
    <script>
        //自执行jq
        $(function () {
            $('#action').click(function () {
                $.get('{% url 'login:json2' %}',

                    function(hh){
                    console.log(hh);
                    $('#user').html(hh['a']);
                    $('#pwd').html(hh['b']);
            })
            })
        })
    </script>>

</head>
<body>
    <button id="action">获取登录的账号密码</button>

        <h2>获取的账号密码如下：</h2>
        <h3 id="user">账号：点击上方</h3>
        <h3 id="pwd">密码：点击上方</h3>
</body>
</html>

templates/login/json2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>json2接口</title>
</head>
<body>

</body>
</html>

templates/login/layui_demo.html
{% extends "login/base.html" %}
{% block content %}
    <body class="layui-layout-body">
    <div class="layui-body">
    <div class="layui-layout layui-layout-admin">
            <!-- 内容主体区域 -->
            <div style="padding: 15px;">内容主体区域
                <form class="layui-form layui-form-pane" lay-filter="first">

                    <div class="layui-form-item">
                        <label class="layui-form-label">输入框title</label>
                        <div class="layui-input-inline" style="width: 600px;">
                            <input type="text" name="title" lay-verify="required|title" placeholder="请输入标题"
                                   autocomplete="off"
                                   class="layui-input">
                        </div>
                        <div class="layui-word-aux">标题长度大于7位</div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">范围money</label>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="price_min" lay-verify="required|money" placeholder="最小金额"
                                   autocomplete="off"
                                   class="layui-input">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <div class="layui-input-inline" style="width: 100px;">
                            <input type="text" name="price_max" lay-verify="required|money" placeholder="最大金额"
                                   autocomplete="off"
                                   class="layui-input">
                        </div>
                        <div class="layui-word-aux">金额必须为小数保留两位</div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">手机号phone</label>
                        <div class="layui-input-inline" style="width: 300px;">
                            <input type="text" name="phone" lay-verify="required|phone" placeholder="请输入手机号"
                                   autocomplete="off"
                                   class="layui-input">
                        </div>
                        <div class="layui-form-mid layui-word-aux">11位手机号</div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">密码框pawd</label>
                        <div class="layui-input-inline" style="width: 300px;">
                            <input type="password" name="password" lay-verify="required|pass" placeholder="请输入密码"
                                   autocomplete="off"
                                   class="layui-input">
                        </div>
                        <div class="layui-form-mid layui-word-aux">六位以上数字加字母密码</div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">邮箱email</label>
                        <div class="layui-input-inline" style="width: 300px;">
                            <input type="text" name="email" lay-verify="required|email" placeholder="请输入邮箱"
                                   autocomplete="off"
                                   class="layui-input">
                        </div>
                        <div class="layui-form-mid layui-word-aux">邮箱</div>
                    </div>

                    <div class="layui-form-item">
                        <label class="layui-form-label">选择框city</label>
                        <div class="layui-input-block">
                            <select name="city" lay-verify="required" lay-search>
                                <option value=""></option>
                                <option id="1" value="北京">北京</option>
                                <option id="2" value="上海">上海</option>
                                <option id="3" value="广州">广州</option>
                                <option id="4" value="深圳">深圳</option>
                                <option id="5" value="杭州">杭州</option>
                            </select>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">复选框</label>
                        <div class="layui-input-block">
                            <input type="checkbox" name="hobbies" value="写作" title="写作">
                            <input type="checkbox" name="hobbies" value="阅读" title="阅读" checked>
                            <input type="checkbox" name="hobbies" value="发呆" title="发呆">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">开关on</label>
                        <div class="layui-input-block">
                            <input type="checkbox" checked name="on_off" lay-skin="switch" lay-text="ON|OFF">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">单选框sex</label>
                        <div class="layui-input-block">
                            <input type="radio" name="sex" value="男" title="男">
                            <input type="radio" name="sex" value="女" title="女" checked>
                            <input type="radio" name="sex" value="" title="中性" disabled>
                        </div>
                    </div>
                    <div class="layui-form-item layui-form-text">
                        <label class="layui-form-label">文本域text</label>
                        <div class="layui-input-block">
                <textarea name="texts" placeholder="请输入15字以上内容" class="layui-textarea"
                          lay-verify="required|texts"></textarea>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label" style="width: 150px;">按日期搜索time</label>
                            <div class="layui-input-inline">
                                <input type="text" class="layui-input" id="time1" name="time1" placeholder="yyyy-MM-dd">
                            </div>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label" style="width: 150px;">按范围搜索times</label>
                            <div class="layui-input-inline">
                                <input type="text" class="layui-input" id="times" name="times" placeholder=" - ">
                            </div>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <div class="layui-input-block">
                            <button class="layui-btn" lay-submit lay-filter="*">立即提交</button>
                            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                        </div>
                    </div>

                    {% if message %}
                        <div class="alert alert-warning">{{ message }}
                        </div>
                    {% endif %}

                </form>

{#                <script src="{% static "layui-v2.4.3/layui/layui.js" %}"></script>#}
                <script>
                    layui.use(['element', 'form', 'layer', 'jquery'], function () {
                        var $ = layui.jquery;
                        var form = layui.form;
                        var layer = layui.layer;

//注意：导航 依赖 element 模块，否则无法进行功能性操作
                        var element = layui.element;

                        //时间控件
                        layui.use('laydate', function () {
                            var laydate = layui.laydate;
                            //按日期搜索
                            laydate.render({
                                elem: '#time1'
                                , min: -7
                                , max: 7
                                , theme: 'molv'
                            });
                            //按范围搜索
                            laydate.render({
                                elem: '#times'
                                , theme: 'molv'
                                , range: true
                            });
                        });

                        //自定义验证规则
                        form.verify({
                            title: function (value) {
                                if (value.length < 7) {
                                    return '标题也太短了吧';

                                }
                            },
                            texts: function (value) {
                                if (value.length < 10) {
                                    return '文本框最少15字';
                                }
                            },
                            pass: [/^[A-Za-z0-9]{6,}$/, '六位以上数字加字母密码'

                            ],

                            money: [
                                /^\d+\.\b\d{2}\b$/, '金额必须为小数保留两位'
                            ]
                        })
                        ;

                        //初始赋值
                        form.val('first', {
                            'title': '测试/初始值'
                            {#, 'desc': '初始9个实需10字'#}

                        });


                        //监听提交

                        form.on('submit(*)', function (data) {
                            $.ajax({
                                url: "{% url 'login:submit_form' %}",
                                type: 'post',
                                dataType: 'json',
                                data: $(data.form).serialize(),
                                {#data: JSON.stringify(data.field),#}

                                success: function (arg) {
                                    if (arg.status === 200) {
                                        layer.msg(arg.msg);
                                        window.location.reload()
                                    } else {
                                        layer.msg(arg.msg)
                                    }
                                },
                                error: function (arg) {
                                    console.log(arg);
                                    layer.msg("系统错误")
                                }
                            });
                            //ajax 提交

                            console.log(data);
                            {#layer.msg(JSON.stringify(data.field));#}
                            return false;
                        });


                    });


                </script>


            </div>
        </div>

        <div class="layui-footer">
            <!-- 底部固定区域 -->
            © layui.com - 底部固定区域
        </div>
    </div>
    </body>


{% endblock %}

templates/login/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>login</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}"/>
    <!--必要样式-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/component.css' %}"/>
    <!--[if IE]>
<script src="/static/js/html5.js"></script>
<![endif]-->
</head>
<body>
<div class="container demo-1">
    <div class="content">
        <div id="large-header" class="large-header">
            <canvas id="demo-canvas"></canvas>
            <div class="logo_box">


                <h3>接口管理平台</h3>
                <form action="{% url 'login:login' %}" name="login" method="post">
                    {% csrf_token %}   <!--加入这行 -->
                    <div class="input_outer">
                        <span class="u_user"></span>
                        <input name="username" class="text" style="color: #FFFFFF !important" type="text"
                               placeholder="请输入账户">
                    </div>
                    <div class="input_outer">
                        <span class="us_uer"></span>
                        <input name="password" class="text"
                               style="color: #FFFFFF !important; position:absolute; z-index:100;" value=""
                               type="password" placeholder="请输入密码">
                    </div>
                    <div class="mb2" align="center">

                        <button class="act-but submit" style="color: #FFFFFF ">登录</button>

                    </div>
                    {#加入了message插件#}
                    {% if message %}
                        <div class="alert alert-warning">{{ message }}
                        </div>
                    {% endif %}
                    {#                      href="javascript:void(0);" onclick="loginCheck()"  #}
                    {#                        <button onclick="loginCheck()">登录</button>#}
                </form>
            </div>
        </div>
    </div>
</div><!-- /container -->
<script src="{% static 'js/TweenLite.min.js' %}"></script>
<script src="{% static 'js/EasePack.min.js' %}"></script>
<script src="{% static 'js/rAF.js' %}"></script>
<script src="{% static 'js/demo-1.js' %}"></script>
<div style="text-align:center;">
    <p>更多模板：<a href="http://www.mycodes.net/" target="_blank">源码之家</a></p>
</div>
</body>
</html>

templates/login/table.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ajax获取列表数据</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/1.4.0/jquery.js"></script>
</head>
<body>
<table class="table table-bordered" id='table'>
    <tr>
        <th>名字</th>
        <th>开始时间</th>
        <th>是否真实</th>
        <th>设备</th>
    </tr>
</table>
<script>
    var obj = {
        '0': '你',
        '1': '我',
        '2': '他'
    };
   //自执行ajax
    $(function () {
        $.ajax({
            url: '{% static 'json/data.json' %}',
            type: 'get',
            dataType: 'json',
            success: function (data) {
                $.each(data.data, function (index, item) {
                    item.is_true = obj[item.is_true];
                    console.log(item.is_true);
                    var arr = item.device.split(":");
                    item.device = arr[1];
                    console.log(item.device);
                    var tr;
                    tr = '<td>' + item.name + '</td>' + '<td>' + item.startTime + '</td>' + '<td>' + item.is_true + '</td>' + '<td>' + item.device + '</td>';
                    $("#table").append('<tr>' + tr + '</tr>')

                })
            },
            error: function () {
                console.log('failed')

            }
        })

    })
</script>
</body>
</html>

templates/login/user_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>